services:
  db:
    image: postgres:12.2-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - PGUSER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 2s
      timeout: 2s
      retries: 3

  movie_bot:
    image: movie_bot
    build:
      context: .
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
